apache/openserverless-site

.asf.yaml
=> Adjusting Publishing staging website

.github/workflows/build.yml
=> adjusting build pipeline hugo

.github/workflows/build.yml
=> adjusting workflows 2

hugo.yaml
Fixed Reddit address (missing .com)
=> Update hugo.yaml to resolve reddit typo

DISCLAIMER, NOTICE
This will fix https://github.com/apache/openserverless/issues/22
=> chore(site): added missing DISCLAIMER and NOTICE

.github/workflows/build.yml
=> fix: github action

.github/workflows/build.yml, content/en/blog/releases/_index.md, hugo.yaml
All websites must link to the Privacy Policy, so I added the missing link
=> Added privacy link

content/en/docs/installation/prereq/docker/_index.md, content/en/docs/installation/quickstart/_index.md, content/en/docs/reference/_index.md, content/en/docs/reference/references/actions-actionloop/_index.md, content/en/docs/reference/references/actions-new/_index.md, content/en/docs/reference/references/advanced-cli/_index.md, content/en/docs/reference/references/naming-limits/_index.md, content/en/docs/reference/references/rest_api/_index.md, content/en/docs/reference/references/scheduler/_index.md, content/en/docs/reference/runtimes/_index.md
Update nuv and nuvolaris references to ops and openserverless
=> Update nuv and nuvolaris references to ops and openserverless

content/en/docs/installation/prereq/server/generic/_index.md, content/en/docs/reference/entities/_index.md, content/en/docs/reference/entities/annotations/_index.md, content/en/docs/reference/entities/feeds/_index.md, content/en/docs/reference/entities/packages/_index.md, content/en/docs/reference/entities/parameters/_index.md, content/en/docs/reference/entities/webactions/_index.md, content/en/docs/reference/references/actions-actionloop/_index.md, content/en/docs/reference/references/actions-new/_index.md, content/en/docs/reference/references/naming-limits/_index.md, content/en/docs/reference/references/rest_api/_index.md, content/en/docs/reference/references/scheduler/_index.md
fix for nuv and Nuvolaris replacement
=> chore: yet another fix for nuv and Nuvolaris replacement

.github/.asf.prod.yaml, .github/workflows/build.yml
Updated the action to copy the .asf.yaml file inside the publish directory
=> chore: create .asf.yaml

.github/.htaccess, .github/workflows/build.yml, content/en/docs/reference/_index.md, content/en/docs/reference/references/_index.md, content/en/docs/reference/references/actions-actionloop/_index.md, content/en/docs/reference/references/actions-new/_index.md, content/en/docs/reference/references/advanced-cli/_index.md, content/en/docs/reference/references/naming-limits/_index.md, content/en/docs/reference/references/rest_api/_index.md, content/en/docs/reference/references/scheduler/_index.md, content/en/docs/reference/runtimes/_index.md
Fixed links ad frontmatter for reference. tbc
=> chore: reference / advanced

content/en/_index.md
added incubating to main title
=> chore: added incubating

README.md
Filled in some informations in README.md
=> chore: change in README.md

Taskfile.yaml, content/en/docs/reference/references/actions-new/_index.md, content/en/docs/reference/references/advanced-cli/_index.md, content/en/docs/reference/references/naming-limits/_index.md, content/en/docs/reference/references/rest_api/_index.md, content/en/docs/reference/tasks/_index.md, content/en/docs/reference/tasks/admin/_index.md, content/en/docs/reference/tasks/cloud/_index.md, content/en/docs/reference/tasks/cloud/aks/_index.md, content/en/docs/reference/tasks/cloud/aws/_index.md, content/en/docs/reference/tasks/cloud/azcloud/_index.md, content/en/docs/reference/tasks/cloud/eks/_index.md, content/en/docs/reference/tasks/cloud/gcloud/_index.md, content/en/docs/reference/tasks/cloud/gke/_index.md, content/en/docs/reference/tasks/cloud/k3s/_index.md, content/en/docs/reference/tasks/cloud/mk8s/_index.md, content/en/docs/reference/tasks/cloud/osh/_index.md, content/en/docs/reference/tasks/config/_index.md, content/en/docs/reference/tasks/debug/_index.md, content/en/docs/reference/tasks/ide/_index.md, content/en/docs/reference/tasks/setup/_index.md, content/en/docs/reference/tasks/util/_index.md, content/en/docs/reference/tools/base64/_index.md, content/en/docs/reference/tools/datefmt/_index.md, content/en/docs/reference/tools/needupdate/_index.md, content/en/docs/reference/tools/sh/_index.md, content/en/docs/reference/tools/validate/_index.md, hugo.yaml
Reviewed all the Advanced Reference. 
Updated tasks. 
Fixed link on right sidebar
=> DO-NOT-MERGE - WIP 

hugo.yaml
Disabled links on right sidebar
=> chore: disabled repo link

content/en/docs/reference/entities/_index.md, content/en/docs/reference/entities/actions/_index.md, content/en/docs/reference/entities/annotations/_index.md, content/en/docs/reference/entities/feeds/_index.md, content/en/docs/reference/entities/packages/_index.md, content/en/docs/reference/entities/parameters/_index.md, content/en/docs/reference/entities/webactions/_index.md, hugo.yaml
Reviewed entities section. Fixed links, paragraph and other things
=> Reviewed entities

content/en/docs/installation/_index.md, content/en/docs/installation/install/_index.md
Fixed two bad links in installation pages
=> chore: bad links in installation

content/en/blog/news/faas-privacy-power.md, content/en/docs/installation/_index.md, content/en/docs/installation/install/_index.md
Added blog post about OpenServerless - "Apache OpenServerless: A FaaS Solution with Privacy and Power"
=> Added Blog post "Apache OpenServerless: A FaaS Solution with Privacy and Power"

content/en/blog/news/faas-privacy-power.md
=> docs(news): modified blog post

content/en/docs/cli/assets/_index.md, content/en/docs/tutorial/first-steps/_index.md, content/en/docs/tutorial/form-validation/_index.md, content/en/docs/tutorial/notify-message/_index.md
aligned documents based on ref https://github.com/apache/openserverless/issues/36
=> fixed docs for ops util command

content/en/docs/tutorial/use-database/_index.md
added create schema to use database tutorial
=> fix: added create schema to use database tutorial

content/en/docs/tutorial/use-database/_index.md
reateSchema must be executed also
=> chore: createSchema must be executed also

content/en/docs/reference/tasks/admin/_index.md, content/en/docs/reference/tasks/config/_index.md
Updated tasks after milvus addition
=> docs(task): updated tasks - milvus

content/en/docs/reference/tasks/config/_index.md
Updated tasks after milvus config addition
=> docs(task): updated tasks - milvus config

content/en/docs/tutorial/_index.md, content/en/docs/tutorial/first-steps/_index.md, content/en/docs/tutorial/form-validation/_index.md, content/en/docs/tutorial/getting-started/_index.md, content/en/docs/tutorial/notify-message/_index.md, content/en/docs/tutorial/packaging/_index.md, content/en/docs/tutorial/use-database/_index.md
Updated tutorial pages to show a warning
=> docs(chore): added warning to tutorial pages

assets/scss/_styles_project.scss, content/en/docs/tutorial/conclusions/_index.md, content/en/docs/tutorial/form-validation/_index.md, layouts/partials/head.html
Added a conclusions page to the tutorial section
=> Added conclusions page

content/en/docs/reference/tasks/devel/_index.md, content/en/docs/reference/tasks/devel/ferretdb/_index.md, content/en/docs/reference/tasks/devel/minio/_index.md, content/en/docs/reference/tasks/devel/psql/_index.md, content/en/docs/reference/tasks/devel/redis/_index.md, content/en/docs/reference/tasks/env/_index.md, content/en/docs/reference/tasks/ide/_index.md, content/en/docs/reference/tasks/setup/_index.md, content/en/docs/reference/tasks/util/_index.md, layouts/partials/head.html, layouts/partials/theme-toggler.html
=> Updated task

.github/workflows/build.yml, content/en/docs/installation/download/_index.md, content/en/docs/reference/tasks/config/_index.md, content/en/docs/reference/tasks/util/_index.md, hugo.yaml, layouts/partials/theme-toggler.html
- changed telegram to discord
- ops install on windows
- minor graphical improvements
- fix to build pipeline
=> multiple fixes

content/en/docs/_index.md
please merge this PR to make the GH action run again
=> space to build
